copy D:\games\Counter-Strike\cstrike\sound\doors\doormove2.wav				D:\Projects\Mcssp\new\original\doors\doormove2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\bhit_flesh-1.wav                      D:\Projects\Mcssp\new\original\player\bhit_flesh-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\player\bhit_flesh-2.wav                      D:\Projects\Mcssp\new\original\player\bhit_flesh-2.wav                    
copy D:\games\Counter-Strike\cstrike\sound\player\bhit_flesh-3.wav                      D:\Projects\Mcssp\new\original\player\bhit_flesh-3.wav                    
copy D:\games\Counter-Strike\cstrike\sound\player\death6.wav                            D:\Projects\Mcssp\new\original\player\death6.wav                          
copy D:\games\Counter-Strike\cstrike\sound\player\die1.wav                              D:\Projects\Mcssp\new\original\player\die1.wav                            
copy D:\games\Counter-Strike\cstrike\sound\player\die2.wav                              D:\Projects\Mcssp\new\original\player\die2.wav                            
copy D:\games\Counter-Strike\cstrike\sound\player\die3.wav                              D:\Projects\Mcssp\new\original\player\die3.wav                            
copy D:\games\Counter-Strike\cstrike\sound\player\headshot1.wav                         D:\Projects\Mcssp\new\original\player\headshot1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\headshot2.wav                         D:\Projects\Mcssp\new\original\player\headshot2.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\headshot3.wav                         D:\Projects\Mcssp\new\original\player\headshot3.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_dirt1.wav                          D:\Projects\Mcssp\new\original\player\pl_dirt1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_dirt2.wav                          D:\Projects\Mcssp\new\original\player\pl_dirt2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_dirt3.wav                          D:\Projects\Mcssp\new\original\player\pl_dirt3.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_dirt4.wav                          D:\Projects\Mcssp\new\original\player\pl_dirt4.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_grate1.wav                         D:\Projects\Mcssp\new\original\player\pl_grate1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_grate2.wav                         D:\Projects\Mcssp\new\original\player\pl_grate2.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_grate3.wav                         D:\Projects\Mcssp\new\original\player\pl_grate3.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_grate4.wav                         D:\Projects\Mcssp\new\original\player\pl_grate4.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_ladder1.wav                        D:\Projects\Mcssp\new\original\player\pl_ladder1.wav                      
copy D:\games\Counter-Strike\cstrike\sound\player\pl_ladder2.wav                        D:\Projects\Mcssp\new\original\player\pl_ladder2.wav                      
copy D:\games\Counter-Strike\cstrike\sound\player\pl_ladder3.wav                        D:\Projects\Mcssp\new\original\player\pl_ladder3.wav                      
copy D:\games\Counter-Strike\cstrike\sound\player\pl_ladder4.wav                        D:\Projects\Mcssp\new\original\player\pl_ladder4.wav                      
copy D:\games\Counter-Strike\cstrike\sound\player\pl_metal1.wav                         D:\Projects\Mcssp\new\original\player\pl_metal1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_metal2.wav                         D:\Projects\Mcssp\new\original\player\pl_metal2.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_metal3.wav                         D:\Projects\Mcssp\new\original\player\pl_metal3.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_metal4.wav                         D:\Projects\Mcssp\new\original\player\pl_metal4.wav                       
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow1.wav                          D:\Projects\Mcssp\new\original\player\pl_snow1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow2.wav                          D:\Projects\Mcssp\new\original\player\pl_snow2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow3.wav                          D:\Projects\Mcssp\new\original\player\pl_snow3.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow4.wav                          D:\Projects\Mcssp\new\original\player\pl_snow4.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow5.wav                          D:\Projects\Mcssp\new\original\player\pl_snow5.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_snow6.wav                          D:\Projects\Mcssp\new\original\player\pl_snow6.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_step1.wav                          D:\Projects\Mcssp\new\original\player\pl_step1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_step2.wav                          D:\Projects\Mcssp\new\original\player\pl_step2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_step3.wav                          D:\Projects\Mcssp\new\original\player\pl_step3.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_step4.wav                          D:\Projects\Mcssp\new\original\player\pl_step4.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_tile1.wav                          D:\Projects\Mcssp\new\original\player\pl_tile1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_tile2.wav                          D:\Projects\Mcssp\new\original\player\pl_tile2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_tile3.wav                          D:\Projects\Mcssp\new\original\player\pl_tile3.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_tile4.wav                          D:\Projects\Mcssp\new\original\player\pl_tile4.wav                        
copy D:\games\Counter-Strike\cstrike\sound\player\pl_tile5.wav                          D:\Projects\Mcssp\new\original\player\pl_tile5.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\ak47-1.wav                           D:\Projects\Mcssp\new\original\weapons\ak47-1.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\ak47-2.wav                           D:\Projects\Mcssp\new\original\weapons\ak47-2.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\ak47_boltpull.wav                    D:\Projects\Mcssp\new\original\weapons\ak47_boltpull.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\ak47_clipin.wav                      D:\Projects\Mcssp\new\original\weapons\ak47_clipin.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\ak47_clipout.wav                     D:\Projects\Mcssp\new\original\weapons\ak47_clipout.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug-1.wav                            D:\Projects\Mcssp\new\original\weapons\aug-1.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug_boltpull.wav                     D:\Projects\Mcssp\new\original\weapons\aug_boltpull.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug_boltslap.wav                     D:\Projects\Mcssp\new\original\weapons\aug_boltslap.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug_clipin.wav                       D:\Projects\Mcssp\new\original\weapons\aug_clipin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug_clipout.wav                      D:\Projects\Mcssp\new\original\weapons\aug_clipout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\aug_forearm.wav                      D:\Projects\Mcssp\new\original\weapons\aug_forearm.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\awp1.wav                             D:\Projects\Mcssp\new\original\weapons\awp1.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\awp_clipin.wav                       D:\Projects\Mcssp\new\original\weapons\awp_clipin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\awp_clipout.wav                      D:\Projects\Mcssp\new\original\weapons\awp_clipout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\awp_deploy.wav                       D:\Projects\Mcssp\new\original\weapons\awp_deploy.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\boltdown.wav                         D:\Projects\Mcssp\new\original\weapons\boltdown.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\boltpull1.wav                        D:\Projects\Mcssp\new\original\weapons\boltpull1.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\boltup.wav                           D:\Projects\Mcssp\new\original\weapons\boltup.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_beep1.wav                         D:\Projects\Mcssp\new\original\weapons\c4_beep1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_beep2.wav                         D:\Projects\Mcssp\new\original\weapons\c4_beep2.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_beep3.wav                         D:\Projects\Mcssp\new\original\weapons\c4_beep3.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_beep4.wav                         D:\Projects\Mcssp\new\original\weapons\c4_beep4.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_beep5.wav                         D:\Projects\Mcssp\new\original\weapons\c4_beep5.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_click.wav                         D:\Projects\Mcssp\new\original\weapons\c4_click.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_disarm.wav                        D:\Projects\Mcssp\new\original\weapons\c4_disarm.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_disarmed.wav                      D:\Projects\Mcssp\new\original\weapons\c4_disarmed.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_explode1.wav                      D:\Projects\Mcssp\new\original\weapons\c4_explode1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\c4_plant.wav                         D:\Projects\Mcssp\new\original\weapons\c4_plant.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\clipin1.wav                          D:\Projects\Mcssp\new\original\weapons\clipin1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\clipout1.wav                         D:\Projects\Mcssp\new\original\weapons\clipout1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\deagle-1.wav                         D:\Projects\Mcssp\new\original\weapons\deagle-1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\deagle-2.wav                         D:\Projects\Mcssp\new\original\weapons\deagle-2.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\de_clipin.wav                        D:\Projects\Mcssp\new\original\weapons\de_clipin.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\de_clipout.wav                       D:\Projects\Mcssp\new\original\weapons\de_clipout.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\de_deploy.wav                        D:\Projects\Mcssp\new\original\weapons\de_deploy.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\dryfire_pistol.wav                   D:\Projects\Mcssp\new\original\weapons\dryfire_pistol.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\dryfire_rifle.wav                    D:\Projects\Mcssp\new\original\weapons\dryfire_rifle.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\dry_rifle.wav                        D:\Projects\Mcssp\new\original\weapons\dry_rifle.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\elite_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_deploy.wav                     D:\Projects\Mcssp\new\original\weapons\elite_deploy.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_fire.wav                       D:\Projects\Mcssp\new\original\weapons\elite_fire.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_leftclipin.wav                 D:\Projects\Mcssp\new\original\weapons\elite_leftclipin.wav               
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_reloadstart.wav                D:\Projects\Mcssp\new\original\weapons\elite_reloadstart.wav              
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_rightclipin.wav                D:\Projects\Mcssp\new\original\weapons\elite_rightclipin.wav              
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_sliderelease.wav               D:\Projects\Mcssp\new\original\weapons\elite_sliderelease.wav             
copy D:\games\Counter-Strike\cstrike\sound\weapons\elite_twirl.wav                      D:\Projects\Mcssp\new\original\weapons\elite_twirl.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\fiveseven-1.wav                      D:\Projects\Mcssp\new\original\weapons\fiveseven-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\fiveseven_sliderelease.wav           D:\Projects\Mcssp\new\original\weapons\fiveseven_sliderelease.wav         
copy D:\games\Counter-Strike\cstrike\sound\weapons\fiveseven_slidepull.wav              D:\Projects\Mcssp\new\original\weapons\fiveseven_slidepull.wav            
copy D:\games\Counter-Strike\cstrike\sound\weapons\fiveseven_clipout.wav                D:\Projects\Mcssp\new\original\weapons\fiveseven_clipout.wav              
copy D:\games\Counter-Strike\cstrike\sound\weapons\fiveseven_clipin.wav                 D:\Projects\Mcssp\new\original\weapons\fiveseven_clipin.wav               
copy D:\games\Counter-Strike\cstrike\sound\weapons\flashbang-1.wav                      D:\Projects\Mcssp\new\original\weapons\flashbang-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\flashbang-2.wav                      D:\Projects\Mcssp\new\original\weapons\flashbang-2.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\g3sg1-1.wav                          D:\Projects\Mcssp\new\original\weapons\g3sg1-1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\g3sg1_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\g3sg1_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\g3sg1_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\g3sg1_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\g3sg1_slide.wav                      D:\Projects\Mcssp\new\original\weapons\g3sg1_slide.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\generic_reload.wav                   D:\Projects\Mcssp\new\original\weapons\generic_reload.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\generic_shot_reload.wav              D:\Projects\Mcssp\new\original\weapons\generic_shot_reload.wav            
copy D:\games\Counter-Strike\cstrike\sound\weapons\glock18-1.wav                        D:\Projects\Mcssp\new\original\weapons\glock18-1.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\glock18-2.wav                        D:\Projects\Mcssp\new\original\weapons\glock18-2.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\grenade_hit1.wav                     D:\Projects\Mcssp\new\original\weapons\grenade_hit1.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\grenade_hit2.wav                     D:\Projects\Mcssp\new\original\weapons\grenade_hit2.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\grenade_hit3.wav                     D:\Projects\Mcssp\new\original\weapons\grenade_hit3.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\headshot2.wav                        D:\Projects\Mcssp\new\original\weapons\headshot2.wav                      
copy D:\games\Counter-Strike\cstrike\sound\weapons\hegrenade-1.wav                      D:\Projects\Mcssp\new\original\weapons\hegrenade-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\hegrenade-2.wav                      D:\Projects\Mcssp\new\original\weapons\hegrenade-2.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\he_bounce-1.wav                      D:\Projects\Mcssp\new\original\weapons\he_bounce-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_deploy1.wav                    D:\Projects\Mcssp\new\original\weapons\knife_deploy1.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_hit1.wav                       D:\Projects\Mcssp\new\original\weapons\knife_hit1.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_hit2.wav                       D:\Projects\Mcssp\new\original\weapons\knife_hit2.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_hit3.wav                       D:\Projects\Mcssp\new\original\weapons\knife_hit3.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_hit4.wav                       D:\Projects\Mcssp\new\original\weapons\knife_hit4.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_hitwall1.wav                   D:\Projects\Mcssp\new\original\weapons\knife_hitwall1.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_slash1.wav                     D:\Projects\Mcssp\new\original\weapons\knife_slash1.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_slash2.wav                     D:\Projects\Mcssp\new\original\weapons\knife_slash2.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\knife_stab.wav                       D:\Projects\Mcssp\new\original\weapons\knife_stab.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249-1.wav                           D:\Projects\Mcssp\new\original\weapons\m249-1.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249-2.wav                           D:\Projects\Mcssp\new\original\weapons\m249-2.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249_boxin.wav                       D:\Projects\Mcssp\new\original\weapons\m249_boxin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249_boxout.wav                      D:\Projects\Mcssp\new\original\weapons\m249_boxout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249_chain.wav                       D:\Projects\Mcssp\new\original\weapons\m249_chain.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249_coverdown.wav                   D:\Projects\Mcssp\new\original\weapons\m249_coverdown.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\m249_coverup.wav                     D:\Projects\Mcssp\new\original\weapons\m249_coverup.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\m3-1.wav                             D:\Projects\Mcssp\new\original\weapons\m3-1.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\m3_insertshell.wav                   D:\Projects\Mcssp\new\original\weapons\m3_insertshell.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\m3_pump.wav                          D:\Projects\Mcssp\new\original\weapons\m3_pump.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1-1.wav                           D:\Projects\Mcssp\new\original\weapons\m4a1-1.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_boltpull.wav                    D:\Projects\Mcssp\new\original\weapons\m4a1_boltpull.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_clipin.wav                      D:\Projects\Mcssp\new\original\weapons\m4a1_clipin.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_clipout.wav                     D:\Projects\Mcssp\new\original\weapons\m4a1_clipout.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_deploy.wav                      D:\Projects\Mcssp\new\original\weapons\m4a1_deploy.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_silencer_off.wav                D:\Projects\Mcssp\new\original\weapons\m4a1_silencer_off.wav              
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_silencer_on.wav                 D:\Projects\Mcssp\new\original\weapons\m4a1_silencer_on.wav               
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_unsil-1.wav                     D:\Projects\Mcssp\new\original\weapons\m4a1_unsil-1.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\m4a1_unsil-2.wav                     D:\Projects\Mcssp\new\original\weapons\m4a1_unsil-2.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\mac10-1.wav                          D:\Projects\Mcssp\new\original\weapons\mac10-1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\mac10_boltpull.wav                   D:\Projects\Mcssp\new\original\weapons\mac10_boltpull.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\mac10_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\mac10_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\mac10_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\mac10_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\mp5-1.wav                            D:\Projects\Mcssp\new\original\weapons\mp5-1.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\mp5-2.wav                            D:\Projects\Mcssp\new\original\weapons\mp5-2.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\mp5_clipin.wav                       D:\Projects\Mcssp\new\original\weapons\mp5_clipin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\mp5_clipout.wav                      D:\Projects\Mcssp\new\original\weapons\mp5_clipout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\mp5_slideback.wav                    D:\Projects\Mcssp\new\original\weapons\mp5_slideback.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\p228-1.wav                           D:\Projects\Mcssp\new\original\weapons\p228-1.wav                         
copy D:\games\Counter-Strike\cstrike\sound\weapons\p228_clipin.wav                      D:\Projects\Mcssp\new\original\weapons\p228_clipin.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\p228_clipout.wav                     D:\Projects\Mcssp\new\original\weapons\p228_clipout.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\p228_slidepull.wav                   D:\Projects\Mcssp\new\original\weapons\p228_slidepull.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\p228_sliderelease.wav                D:\Projects\Mcssp\new\original\weapons\p228_sliderelease.wav              
copy D:\games\Counter-Strike\cstrike\sound\weapons\p90-1.wav                            D:\Projects\Mcssp\new\original\weapons\p90-1.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\p90_boltpull.wav                     D:\Projects\Mcssp\new\original\weapons\p90_boltpull.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\p90_clipin.wav                       D:\Projects\Mcssp\new\original\weapons\p90_clipin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\p90_clipout.wav                      D:\Projects\Mcssp\new\original\weapons\p90_clipout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\p90_cliprelease.wav                  D:\Projects\Mcssp\new\original\weapons\p90_cliprelease.wav                
copy D:\games\Counter-Strike\cstrike\sound\weapons\pinpull.wav                          D:\Projects\Mcssp\new\original\weapons\pinpull.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\reload1.wav                          D:\Projects\Mcssp\new\original\weapons\reload1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric1.wav                             D:\Projects\Mcssp\new\original\weapons\ric1.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric2.wav                             D:\Projects\Mcssp\new\original\weapons\ric2.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric3.wav                             D:\Projects\Mcssp\new\original\weapons\ric3.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric4.wav                             D:\Projects\Mcssp\new\original\weapons\ric4.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric5.wav                             D:\Projects\Mcssp\new\original\weapons\ric5.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric_conc-1.wav                       D:\Projects\Mcssp\new\original\weapons\ric_conc-1.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric_conc-2.wav                       D:\Projects\Mcssp\new\original\weapons\ric_conc-2.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric_metal-1.wav                      D:\Projects\Mcssp\new\original\weapons\ric_metal-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\ric_metal-2.wav                      D:\Projects\Mcssp\new\original\weapons\ric_metal-2.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\scout_bolt.wav                       D:\Projects\Mcssp\new\original\weapons\scout_bolt.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\scout_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\scout_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\scout_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\scout_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\scout_fire-1.wav                     D:\Projects\Mcssp\new\original\weapons\scout_fire-1.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg550-1.wav                          D:\Projects\Mcssp\new\original\weapons\sg550-1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg550_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\sg550_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg550_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\sg550_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg550_boltpull.wav                   D:\Projects\Mcssp\new\original\weapons\sg550_boltpull.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg552-1.wav                          D:\Projects\Mcssp\new\original\weapons\sg552-1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg552-2.wav                          D:\Projects\Mcssp\new\original\weapons\sg552-2.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg552_boltpull.wav                   D:\Projects\Mcssp\new\original\weapons\sg552_boltpull.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg552_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\sg552_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg552_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\sg552_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\sg_explode.wav                       D:\Projects\Mcssp\new\original\weapons\sg_explode.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\siderelease1.wav                     D:\Projects\Mcssp\new\original\weapons\siderelease1.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\slideback1.wav                       D:\Projects\Mcssp\new\original\weapons\slideback1.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\sliderelease1.wav                    D:\Projects\Mcssp\new\original\weapons\sliderelease1.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\tmp-1.wav                            D:\Projects\Mcssp\new\original\weapons\tmp-1.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\tmp-2.wav                            D:\Projects\Mcssp\new\original\weapons\tmp-2.wav                          
copy D:\games\Counter-Strike\cstrike\sound\weapons\ump45-1.wav                          D:\Projects\Mcssp\new\original\weapons\ump45-1.wav                        
copy D:\games\Counter-Strike\cstrike\sound\weapons\ump45_clipout.wav                    D:\Projects\Mcssp\new\original\weapons\ump45_clipout.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\ump45_clipin.wav                     D:\Projects\Mcssp\new\original\weapons\ump45_clipin.wav                   
copy D:\games\Counter-Strike\cstrike\sound\weapons\ump45_boltslap.wav                   D:\Projects\Mcssp\new\original\weapons\ump45_boltslap.wav                 
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp1.wav                             D:\Projects\Mcssp\new\original\weapons\usp1.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp2.wav                             D:\Projects\Mcssp\new\original\weapons\usp2.wav                           
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_clipin.wav                       D:\Projects\Mcssp\new\original\weapons\usp_clipin.wav                     
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_clipout.wav                      D:\Projects\Mcssp\new\original\weapons\usp_clipout.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_silencer_off.wav                 D:\Projects\Mcssp\new\original\weapons\usp_silencer_off.wav               
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_silencer_on.wav                  D:\Projects\Mcssp\new\original\weapons\usp_silencer_on.wav                
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_slideback.wav                    D:\Projects\Mcssp\new\original\weapons\usp_slideback.wav                  
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_sliderelease.wav                 D:\Projects\Mcssp\new\original\weapons\usp_sliderelease.wav               
copy D:\games\Counter-Strike\cstrike\sound\weapons\usp_unsil-1.wav                      D:\Projects\Mcssp\new\original\weapons\usp_unsil-1.wav                    
copy D:\games\Counter-Strike\cstrike\sound\weapons\xm1014-1.wav                         D:\Projects\Mcssp\new\original\weapons\xm1014-1.wav                       
copy D:\games\Counter-Strike\cstrike\sound\weapons\zoom.wav                             D:\Projects\Mcssp\new\original\weapons\zoom.wav                           

