copy D:\games\half-life\cstrike\maps\as_tundra.txt .
copy D:\games\half-life\cstrike\maps\as_tundra.bsp .
copy D:\games\half-life\cstrike\maps\cs_estate.bsp .
copy D:\games\half-life\cstrike\maps\cs_estate.txt .
copy D:\games\half-life\cstrike\maps\cs_thunder.bsp .
copy D:\games\half-life\cstrike\maps\cs_thunder.txt .
copy D:\games\half-life\cstrike\maps\de_dust2.bsp .
copy D:\games\half-life\cstrike\maps\de_dust2.txt .
copy D:\games\half-life\cstrike\maps\de_inferno.bsp .
copy D:\games\half-life\cstrike\maps\de_inferno.txt .
copy D:\games\half-life\cstrike\maps\de_nuke.bsp .
copy D:\games\half-life\cstrike\maps\de_nuke.txt .
copy D:\games\half-life\cstrike\maps\de_rotterdam.bsp .
copy D:\games\half-life\cstrike\maps\de_rotterdam.txt .
copy D:\games\half-life\cstrike\maps\de_train.txt .
copy D:\games\half-life\cstrike\maps\de_train.bsp .
copy D:\games\half-life\cstrike\maps\de_vegas.bsp .
copy D:\games\half-life\cstrike\maps\de_vegas.txt .
copy D:\games\half-life\cstrike\maps\de_vertigo.txt .
copy D:\games\half-life\cstrike\maps\de_vertigo.bsp .
