copy V_AK47.MDL        V_AK47_R.MDL
copy V_AWP.MDL         V_AWP_r.MDL
copy V_C4.MDL          V_C4_R.MDL
copy V_DEAGLE.MDL      V_DEAGLE_R.MDL
copy V_FLASHB.MDL      V_FLASHB_R.MDL
copy V_G3SG1.MDL       V_G3SG1_R.MDL
copy V_GLOCK1.MDL      V_GLOCK1_R.MDL
copy v_glock18.mdl     v_glock18_R.mdl
copy V_HEGREN.MDL      V_HEGREN_R.MDL
copy V_KNIFE.MDL       V_KNIFE_R.MDL
copy V_M249.MDL        V_M249_R.MDL
copy V_M3.MDL          V_M3_R.MDL
copy V_M4A1.MDL        V_M4A1_R.MDL
copy V_MP5.MDL         V_MP5_R.MDL
copy V_P228.MDL        V_P228_R.MDL
copy V_P90.MDL         V_P90_R.MDL
copy V_SCOUT.MDL       V_SCOUT_R.MDL
copy V_SG552.MDL       V_SG552_R.MDL
copy V_TMP.MDL         V_TMP_R.MDL
copy V_USP.MDL         V_USP_R.MDL
copy V_XM1014.MDL      V_XM1014_R.MDL
